version: "3.9"

services:
  api:
    build: ./javavuln-api
    ports:
      - "3001:3001"
    networks:
      - javavuln
  site:
    depends_on:
      - api
    build: ./javavuln
    ports:
      - "80:3000"
    networks:
      - javavuln
networks:
  javavuln:
    driver: bridge
