version: "3.9"

services:
  api:
    build: ./javavuln-api
    ports:
      - "3001:3001"
    networks:
      - javavuln
    environment:
      - NODE_ENV=production
      - API_PORT=3001
      - FRONT_END_PORT=80
      - DB_NAME=./vuln.db
  site:
    depends_on:
      - api
    build: ./javavuln
    environment:
      - NODE_ENV=production
      - API_PORT=3001
      - API_ORIGIN=http://api:3001
    ports:
      - "80:3000"
    networks:
      - javavuln
networks:
  javavuln:
    driver: bridge
